import Head from "next/head";
import styles from "../styles/about_me.module.scss";
import Header from "../components/header";
export default function About() {
    return (
        <div className={styles.main_container}>
            <Head>
                <title>My Portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <div className={styles.top}></div>
            <main className={styles.main}>
                <h1>Hi...</h1>
                <p>
                    In 2020 I started this journey throught the webdevelopment
                    industry and so I followed courses on{" "}
                    <a href="https://www.codecademy.com/">Codecademy</a>, keep
                    reading articles on the latest news , and test my knowledge
                    and skills solving challenges on{" "}
                    <a href="#">Frontend Mentor</a>
                    . <br /> I am currently searching for an opportunity to
                    improve my knowledge and experience. I love to learn new
                    skills and face new challenges.
                    <br /> I love nature, so when not coding, you can find me
                    out, whatever it is for a walk, cycling or simly visit new
                    places. I like reading, art and food.
                    <br /> I'd love you to check my work. <br />
                    Thanks for your time.
                </p>
            </main>
            <div className={styles.bottom}></div>
        </div>
    );
}
