import Head from "next/head";
import styles from "../styles/about_me.module.scss";
import Header from "../components/header";
import Link from "next/link";
export default function About() {
    return (
        <div className={styles.main_container}>
            <Head>
                <title>My Portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <div className={styles.top}></div>
            <main className={styles.main}>
                <h1>Hi...</h1>

                <p>
                    In the first half of 2020, I began my journey into the tech
                    industry. I started my journey by completing Javascript,
                    HTML and CSS courses on{" "}
                    <Link href="https://www.codecademy.com/">
                        <a>Codecademy</a>
                    </Link>
                    . In addition, I continue to enjoy and read articles on the
                    latest news in the industry.
                </p>
                <p>
                    To further increase my knowledge, I started to solve
                    challenges on{" "}
                    <Link href="https://www.frontendmentor.io/">
                        <a>Frontend Mentor</a>
                    </Link>{" "}
                    towards the end of 2020, focusing mainly on Typescript,
                    React, and NextJS.
                </p>
                <p>
                    I have continued to improve and increase my knowledge in
                    these areas throughout 2021. I love to learn new skills and
                    face new challenges, and I am always looking for new
                    opportunities to improve even further.
                </p>
                <p>
                    I love nature, so when I'm not coding, you can find me out
                    exploring, whether it's for a walk, cycling or, simply
                    visiting new places. I like reading, art and food.
                </p>
                <p>I'd love it if you checked out my work.</p>
            </main>
            <div className={styles.bottom}></div>
        </div>
    );
}
