import Head from "next/head";
import styles from "../styles/contact.module.scss";
import Link from "next/link";
import Header from "../components/header";

export default function Contact() {
    return (
        <div className={styles.main_container}>
            <Head>
                <title>Portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div className={styles.container_form}>
                <div className={styles.contact_info}>
                    <h2>Contact Me</h2>

                    <p>
                        I am currently looking for a work from home position,
                        but I would be open to other oppprtunities that don't
                        fit it. I work hard to solve problems and I like to pay
                        attention to each details of a projects. So let's get in
                        touch!
                    </p>
                </div>

                <form className={styles.form} noValidate>
                    <label htmlFor="name">NAME</label>
                    <input
                        id="name"
                        type="text"
                        name="name"
                        placeholder="Name"
                    />

                    <label htmlFor="email">EMAIL</label>
                    <input
                        id="emai"
                        type="text"
                        name="email"
                        placeholder="email@example.com"
                    />
                    <label htmlFor="email">MESSAGE</label>
                    <textarea
                        id="message"
                        name="message"
                        placeholder=" Leave a message here"
                        className={styles.message}
                    ></textarea>

                    <button
                        type="submit"
                        aria-label="button"
                        className={styles.contact_btn}
                    >
                        CONTACT ME
                    </button>
                </form>
            </div>
            <div className={styles.cube_wrapper}>
                <span className={styles.cube}></span>
                <span className={styles.cube}></span>
                <span className={styles.cube}></span>
                <span className={styles.cube}></span>
                <span className={styles.cube}></span>
                <span className={styles.cube}></span>
            </div>
        </div>
    );
}
