import Head from "next/head";
import styles from "../styles/portfolio.module.scss";
import Header from "../components/header";
import Work from "../components/work";
import Git from "../svg/github.svg";
import { useState } from "react";
import Link from "next/link";
export default function Portfolio() {
    return (
        <div className={styles.main_container}>
            <Head>
                <title>My Portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <main className={styles.main}>
                <h1>Portfolio</h1>

                <p>
                    Below you will find a collection of challenges I have solved
                    from{" "}
                    <Link href="https://www.frontendmentor.io/">
                        <a> Frontend Mentor</a>
                    </Link>
                    . Each of these challenges presented new problems for me to
                    solve and increased my knowledge and understanding further.
                    These challenges allowed me to explore Typescript, React and
                    NextJS to the fullest and taught me how to use them
                    effectively to solve the problem.
                </p>
                <p>
                    To see more of my work, please visit my profile on{" "}
                    <Link href="https://www.frontendmentor.io/profile/Andro87">
                        <a>Frontend Mentor</a>
                    </Link>{" "}
                    or{" "}
                    <Link href="https://github.com/Andro87">
                        <a> GitHub</a>
                    </Link>
                    .
                </p>
            </main>
            <section className={styles.section_work}>
                <hr className={styles.hr_line} />
                <div className={styles.work_container}>
                    <Work
                        image={
                            <img
                                src="/images/screenshots/room_homepage.png"
                                alt="room home page"
                            />
                        }
                        href="https://git-room-homepage.vercel.app/"
                        project="ROOM HOMEPAGE"
                        language="HTML / SCSS / TSX"
                        info=" This project required to build a responsive
                                    website and to navigate throught the slides. "
                    />

                    <Work
                        image={
                            <img
                                src="/images/screenshots/loopstudios-landing-page.png"
                                alt="loopstudios"
                            />
                        }
                        href="https://loopstudios-landing-page-ten.vercel.app/"
                        project="LOOPSTUDIOS"
                        language="HTML / SCSS / TSX"
                        info="This project was a big test for layout
                                    skills, and it also required a bit of JS for
                                    the mobile's menu button."
                    />

                    <Work
                        image={
                            <img
                                src="/images/screenshots/typemaster.png"
                                alt="typemaster"
                            />
                        }
                        href="https://typemaster-pre-launch-landing-page-five.vercel.app/"
                        project="TYPEMASTER"
                        language="HTML / SCSS / TSX"
                        info="In  this project the layout shifts for each device , a  great test for css skills. "
                    />

                    <Work
                        image={
                            <img
                                src="/images/screenshots/sunnyside-agency-landing-page.png"
                                alt="sunny side agency"
                            />
                        }
                        href="https://sunnyside-agency-landing-page-green.vercel.app/"
                        project="SUNNYSIDE AGENCY"
                        language="HTML / SCSS / TSX"
                        info="This project was a test for layout skills and little details. "
                    />

                    <Work
                        image={
                            <img
                                src="/images/screenshots/pod-request.png"
                                alt="pod request"
                            />
                        }
                        href="https://pod-request-access-landing-lage.vercel.app/"
                        project="POD REQUEST ACCESS"
                        language="HTML / SCSS / TSX"
                        info="This project was a nice test for responsiveness and also required a bit of JS for custum for validation."
                    />

                    <Work
                        image={
                            <img
                                src="/images/screenshots/creative-single-page.png"
                                alt="creative single page"
                            />
                        }
                        href="https://creative-single-page-site-psi.vercel.app/"
                        project="CREATIVE SINGLE PAGE SITE"
                        language="HTML / SCSS / TSX"
                        info="This project has lots of overlapping elemts. A great challenge for layout skills. "
                    />

                    <Work
                        image={
                            <img
                                src="/images/screenshots/insure-landing-page-ruddy.vercel.app_ (1).png"
                                alt="creative single page"
                            />
                        }
                        href="https://insure-landing-page-ruddy.vercel.app/"
                        project="INSURE LANDING PAGE"
                        language="HTML / SCSS / TSX"
                        info="This project has been a good  test for layout skills. "
                    />
                </div>
            </section>
        </div>
    );
}
